<?php

namespace AppBundle\Repository;

/**
 * PostcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPartialPostcode($pPostcode){
        $em =  $this->getEntityManager();
        $raw = 'SELECT * FROM postcode p where postcode LIKE :post ORDER BY p.postcode ASC';
        
        $statement = $em->getConnection()->prepare($raw);
        
        $statement->bindValue('post', "%".$pPostcode."%");
        $statement->execute();

        return $statement->fetchAll();
        
    }
    
    public function findByLatLonPostcode($lat,$lon){
        $qb =  $this->createQueryBuilder('p');
        $qb->select('p.id,p.postcode,p.lat,p.lon');

        $qb->where('p.lat = :lat and p.lon = :lon');

        $qb->setParameter('lat',$lat);
        $qb->setParameter('lon',$lon);

        return $qb->getQuery()->getResult();
        
    }
}
