<?php

namespace AppBundle\Repository;

/**
 * PostcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPartialPostcode($pPostcode){
        $em =  $this->getEntityManager();
        $raw = 'SELECT * FROM postcode p where postcode LIKE :post ORDER BY p.postcode ASC';
        
        $statement = $em->getConnection()->prepare($raw);
        
        $statement->bindValue('post', "%".$pPostcode."%");
        $statement->execute();

        return $statement->fetchAll();
        
    }
    
    public function findByLatLonPostcode($lat,$lon){
        $em =  $this->getEntityManager();
        $raw = 'SELECT * FROM postcode p where lat = :lat and lon = :lon ORDER BY p.postcode ASC';
        
        $statement = $em->getConnection()->prepare($raw);
        
        $statement->bindValue('lat',$lat);
        $statement->bindValue('lon',$lon);
        $statement->execute();

        return $statement->fetchAll();
        
    }
}
